logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: client-id
            client-secret: client-secret
            scope: public_repo
            redirect-uri-template: "{baseUrl}/authorize/oauth2/code/github"
            client-name: GitHub Repositories
