#Transaction log data source.
targetDataSource:
  ds_trans_0: !!org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds_trans_0?serverTimezone=UTC&useSSL=false
    username: root
    password:
  ds_trans_1: !!org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds_trans_1?serverTimezone=UTC&useSSL=false
    username: root
    password:

#Data source for transaction manager.
transactionLogDataSource:
  ds_trans: !!org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trans_log?serverTimezone=UTC&useSSL=false
    username: root
    password:

jobConfig:
  #job name
  name: BASETransaction
  
  #cron expression
  cron: 0/5 * * * * ?
  
  #The maximum number of transaction logs fetch from each job
  transactionLogFetchDataCount: 100
  
  #The maximum number of try to deliver a transaction.
  maxDeliveryTryTimes: 3
  
  #The milliseconds of delay delivery of the transaction.
  maxDeliveryTryDelayMillis: 60000
