server:
  port: 7020
management:
  port: 9218
  context-path: '/e58a0ff5-9f60-4545-9aa2-2b91c8a6d53b'
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka1:8763/eureka/,http://eureka2:8762/eureka/'
    registry-fetch-interval-seconds: 5
  instance:
    metadata-map:
      cluster: prontera
      management:
        port: ${management.port}
        context-path: ${management.context-path}
      health:
        path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: 'spring-boot-admin'
  cloud:
    loadbalancer:
      retry:
        enabled: true
  boot:
    admin:
      turbine:
        url: 'http://hystrix_dashboard:8193/turbine.stream'
        clusters: 'prontera'
